#!/bin/bash

exec docker run --rm \
    --net host \
    --privileged \
    -e DISPLAY=unix$DISPLAY \
    -v /tmp/.X11-unix:/tmp/.X11-unix:ro \
    -v /mnt/docker-data/configs/genymotion:/home/vu \
    --name genymotion \
    thenewvu/genymotion
